// Steam public tag catalogue: https://store.steampowered.com/tag/browse/?l=english
// Snapshot: 2026-10-01. Custom values remain supported.
export const STEAM_TAG_OPTIONS: string[] = [
  "Indie",
  "Action",
  "Adventure",
  "Casual",
  "Singleplayer",
  "Simulation",
  "RPG",
  "Strategy",
  "2D",
  "3D",
  "Early Access",
  "Free to Play",
  "Atmospheric",
  "Story Rich",
  "Colorful",
  "Exploration",
  "Fantasy",
  "Multiplayer",
  "Cute",
  "Pixel Graphics",
  "Combat",
  "First-Person",
  "Puzzle",
  "Stylized",
  "Relaxing",
  "Action-Adventure",
  "Funny",
  "Arcade",
  "Controller",
  "Anime",
  "PvE",
  "Horror",
  "Sci-fi",
  "Co-op",
  "Sports",
  "Choices Matter",
  "Third Person",
  "Massively Multiplayer",
  "Top-Down",
  "Retro",
  "Family Friendly",
  "Violent",
  "Shooter",
  "Female Protagonist",
  "PvP",
  "Dark",
  "Sexual Content",
  "Realistic",
  "Online Co-Op",
  "Mystery",
  "Multiple Endings",
  "Racing",
  "Character Customization",
  "Linear",
  "Survival",
  "Open World",
  "Nudity",
  "Physics",
  "Comedy",
  "Cartoony",
  "Visual Novel",
  "Psychological Horror",
  "Gore",
  "Platformer",
  "Roguelike",
  "Magic",
  "Roguelite",
  "2D Platformer",
  "Resource Management",
  "Management",
  "Sandbox",
  "Tactical",
  "Old School",
  "Medieval",
  "Hand-drawn",
  "FPS",
  "Minimalist",
  "Immersive Sim",
  "Action RPG",
  "Turn-Based Combat",
  "Crafting",
  "Turn-Based Strategy",
  "Building",
  "Futuristic",
  "Point & Click",
  "Dark Fantasy",
  "Emotional",
  "Action Roguelike",
  "Procedural Generation",
  "Cartoon",
  "Space",
  "Difficult",
  "3D Platformer",
  "Interactive Fiction",
  "Nature",
  "Romance",
  "Choose Your Own Adventure",
  "Logic",
  "Turn-Based Tactics",
  "Survival Horror",
  "Utilities",
  "Incremental",
  "Local Multiplayer",
  "Base Building",
  "1990's",
  "Hentai",
  "Surreal",
  "Hack and Slash",
  "Hidden Object",
  "Dating Sim",
  "Bullet Hell",
  "Post-apocalyptic",
  "VR",
  "Lore-Rich",
  "Strategy RPG",
  "Side Scroller",
  "Economy",
  "Dungeon Crawler",
  "Life Sim",
  "Walking Simulator",
  "Education",
  "Inventory Management",
  "Score Attack",
  "Card Game",
  "Puzzle Platformer",
  "Tabletop",
  "Cinematic",
  "Dialogue Heavy",
  "Text-Based",
  "Idler",
  "War",
  "Psychological",
  "Shoot 'Em Up",
  "Stealth",
  "Zombies",
  "JRPG",
  "LGBTQ+",
  "Investigation",
  "Design & Illustration",
  "1980s",
  "Great Soundtrack",
  "Local Co-Op",
  "Historical",
  "Thriller",
  "2.5D",
  "Supernatural",
  "Party-Based RPG",
  "Deckbuilding",
  "Time Management",
  "Tutorial",
  "Isometric",
  "Dark Humor",
  "Artificial Intelligence",
  "Nonlinear",
  "Replay Value",
  "Military",
  "Cozy",
  "Loot",
  "Team-Based",
  "Top-Down Shooter",
  "Turn-Based",
  "Third-Person Shooter",
  "Demons",
  "Collectathon",
  "Aliens",
  "Tactical RPG",
  "Cyberpunk",
  "Detective",
  "Robots",
  "Modern",
  "Software",
  "Real Time Tactics",
  "Dystopian",
  "Tower Defense",
  "Perma Death",
  "Abstract",
  "Driving",
  "Automation",
  "Board Game",
  "RTS",
  "Card Battler",
  "CRPG",
  "Precision Platformer",
  "Arena Shooter",
  "Comic Book",
  "Souls-like",
  "Psychedelic",
  "City Builder",
  "Capitalism",
  "Cats",
  "Co-op Campaign",
  "Mythology",
  "Wargame",
  "Memes",
  "Alternate History",
  "Creature Collector",
  "4 Player Local",
  "Grid-Based Movement",
  "Dragons",
  "Game Development",
  "Crime",
  "Destruction",
  "Level Editor",
  "Class-Based",
  "Fast-Paced",
  "Short",
  "Moddable",
  "Party Game",
  "Parkour",
  "Flight",
  "Beat 'em up",
  "Metroidvania",
  "Animation & Modeling",
  "Trading",
  "Music",
  "Philosophical",
  "Auto Battler",
  "Runner",
  "Dark Comedy",
  "Cooking",
  "Farming Sim",
  "2D Fighter",
  "Automobile Sim",
  "Rhythm",
  "Gun Customization",
  "3D Fighter",
  "Soundtrack",
  "Competitive",
  "Vehicular Combat",
  "Swordplay",
  "Wholesome",
  "eSports",
  "Fighting",
  "MMORPG",
  "Conspiracy",
  "Quick-Time Events",
  "Noir",
  "Science",
  "Lovecraftian",
  "Colony Sim",
  "Word Game",
  "Twin Stick Shooter",
  "Mining",
  "Satire",
  "Space Sim",
  "Gothic",
  "Narrative",
  "Grand Strategy",
  "Parody",
  "Dynamic Narration",
  "Underground",
  "Video Production",
  "Looter Shooter",
  "Experimental",
  "Roguelike Deckbuilder",
  "Audio Production",
  "Agriculture",
  "Shop Keeper",
  "Fishing",
  "Split Screen",
  "Mystery Dungeon",
  "Classic",
  "Battle Royale",
  "6DOF",
  "Bullet Time",
  "World War II",
  "Gambling",
  "Time Manipulation",
  "Martial Arts",
  "Immersive",
  "Spectacle fighter",
  "Asynchronous Multiplayer",
  "Mechs",
  "Transportation",
  "Combat Racing",
  "Voxel",
  "Dogs",
  "Animals",
  "Match 3",
  "Action RTS",
  "Beautiful",
  "Hero Shooter",
  "FMV",
  "Trading Card Game",
  "Open World Survival Craft",
  "Vampires",
  "Time Travel",
  "Ninja",
  "God Game",
  "Solitaire",
  "Underwater",
  "Pirates",
  "Steampunk",
  "Otome",
  "Bullet Heaven",
  "Hex Grid",
  "Boomer Shooter",
  "Political Sim",
  "Hacking",
  "Hunting",
  "Job Simulator",
  "Software Training",
  "Trains",
  "Typing",
  "Faith",
  "Tanks",
  "Programming",
  "Party",
  "4X",
  "MOBA",
  "Sokoban",
  "Assassins",
  "Diplomacy",
  "Remake",
  "Superhero",
  "Minigames",
  "Western",
  "Photo Editing",
  "Dinosaurs",
  "Traditional Roguelike",
  "Heist",
  "Mouse Only",
  "Character Action Game",
  "Naval",
  "Snow",
  "Cold War",
  "Transhumanism",
  "Sailing",
  "Naval Combat",
  "Escape Room",
  "Music-Based Procedural Generation",
  "Archery",
  "Nostalgia",
  "Farming",
  "Horses",
  "Addictive",
  "Real-Time",
  "Football (Soccer)",
  "Desktop Companion",
  "Trivia",
  "Organizing",
  "Episodic",
  "Werewolves",
  "Offroad",
  "Villain Protagonist",
  "Time Attack",
  "Epic",
  "Real-Time with Pause",
  "Sniper",
  "On-Rails Shooter",
  "Spelling",
  "Sequel",
  "Dwarves",
  "Outbreak Sim",
  "Spaceships",
  "Cleaning",
  "Decorating",
  "World War I",
  "Mars",
  "Chess",
  "Jump Scare",
  "Boxing",
  "Dice",
  "Extraction Shooter",
  "Social Deduction",
  "Mod",
  "Medical Sim",
  "Basketball",
  "Submarine",
  "Touch-Friendly",
  "Golf",
  "Motorbike",
  "Gaming",
  "Baseball",
  "Pinball",
  "Rome",
  "Elves",
  "Boss Rush",
  "360 Video",
  "Bikes",
  "Electronic Music",
  "Asymmetric VR",
  "Wrestling",
  "Xianxia",
  "Wuxia",
  "Skateboarding",
  "Cult",
  "Vikings",
  "Instrumental Music",
  "Silent Protagonist",
  "Billiards",
  "Mini Golf",
  "Football (American)",
  "Skating",
  "Espionage",
  "Poker",
  "Hobby Sim",
  "Rock Music",
  "Falling Blocks",
  "Cycling",
  "Birds",
  "Samurai",
  "Mahjong",
  "Tennis",
  "Intentionally Awkward Controls",
  "Motocross",
  "Foxes",
  "TrackIR",
  "Hockey",
  "Hardware",
  "Bowling",
  "Language Learning",
  "Voice Control",
  "Skiing",
  "Snowboarding",
  "Based On A Novel",
  "ATV",
  "Lemmings",
  "8-bit Music",
  "BMX",
  "Wolves",
  "Musou",
  "Benchmark",
  "Capybaras",
  "Zoo",
  "Volleyball",
  "Cricket",
  "Rugby",
  "Reboot"
];

export const GAME_FIELD_OPTIONS: Record<string, string[]> = {
  "genres": [
    "Action",
    "Adventure",
    "Casual",
    "Indie",
    "Massively Multiplayer",
    "Racing",
    "RPG",
    "Simulation",
    "Sports",
    "Strategy",
    "Action-Adventure",
    "Action RPG",
    "Action Roguelike",
    "Action RTS",
    "Arcade",
    "Arena Shooter",
    "Auto Battler",
    "Battle Royale",
    "Beat 'em up",
    "Boomer Shooter",
    "Bullet Hell",
    "Bullet Heaven",
    "Card Battler",
    "Card Game",
    "Character Action Game",
    "City Builder",
    "Colony Sim",
    "CRPG",
    "Dating Sim",
    "Deckbuilding",
    "Dungeon Crawler",
    "Extraction Shooter",
    "Farming Sim",
    "Fighting",
    "FPS",
    "God Game",
    "Grand Strategy",
    "Hack and Slash",
    "Hero Shooter",
    "Hidden Object",
    "Immersive Sim",
    "Interactive Fiction",
    "JRPG",
    "Life Sim",
    "Looter Shooter",
    "Management",
    "Metroidvania",
    "MMORPG",
    "MOBA",
    "Mystery Dungeon",
    "Open World Survival Craft",
    "Party Game",
    "Party-Based RPG",
    "Platformer",
    "Point & Click",
    "Precision Platformer",
    "Puzzle",
    "Puzzle Platformer",
    "Real Time Tactics",
    "Roguelike",
    "Roguelike Deckbuilder",
    "Roguelite",
    "RTS",
    "Sandbox",
    "Shoot 'Em Up",
    "Shooter",
    "Souls-like",
    "Space Sim",
    "Stealth",
    "Strategy RPG",
    "Survival",
    "Survival Horror",
    "Tactical RPG",
    "Third-Person Shooter",
    "Tower Defense",
    "Traditional Roguelike",
    "Turn-Based Strategy",
    "Turn-Based Tactics",
    "Twin Stick Shooter",
    "Visual Novel",
    "Walking Simulator",
    "Wargame",
    "2D Fighter",
    "2D Platformer",
    "3D Fighter",
    "3D Platformer",
    "4X"
  ],
  "tags": STEAM_TAG_OPTIONS,
  "keyFeatures": [
    "Singleplayer",
    "Multiplayer",
    "Online Co-Op",
    "Local Co-Op",
    "Co-op Campaign",
    "Cross-Platform Multiplayer",
    "Shared/Split Screen",
    "PvP",
    "PvE",
    "Controller",
    "Full Controller Support",
    "Steam Achievements",
    "Steam Cloud",
    "Steam Trading Cards",
    "Steam Workshop",
    "Remote Play Together",
    "Remote Play on Phone",
    "Remote Play on Tablet",
    "Remote Play on TV",
    "VR Support",
    "VR Only",
    "Steam Leaderboards",
    "Level Editor",
    "Moddable",
    "Character Customization",
    "Gun Customization",
    "Procedural Generation",
    "Open World",
    "Crafting",
    "Base Building",
    "Resource Management",
    "Inventory Management",
    "Multiple Endings",
    "Choices Matter",
    "Branching Dialogue",
    "Story Rich",
    "Replay Value",
    "Daily Challenges",
    "New Game Plus",
    "Photo Mode",
    "Difficulty Options",
    "Subtitles",
    "Customizable Controls",
    "Ultrawide Support",
    "Colorblind Options",
    "Text-to-Speech",
    "Adjustable Text Size",
    "Save Anywhere",
    "Turn-Based Combat",
    "Real-Time Combat",
    "Building",
    "Destruction",
    "Physics",
    "Trading",
    "Exploration",
    "Collectathon",
    "Loot",
    "Skill Trees",
    "Class-Based",
    "Team-Based",
    "Asynchronous Multiplayer",
    "4 Player Local",
    "Split Screen",
    "Tutorial",
    "Automation",
    "Dynamic Narration",
    "Time Manipulation",
    "Music-Based Procedural Generation",
    "Co-op Multiplayer",
    "Procedural Level Generation",
    "Community Mod Support"
  ],
  "supportedLanguages": [
    "English",
    "French",
    "Italian",
    "German",
    "Spanish - Spain",
    "Spanish - Latin America",
    "Arabic",
    "Bulgarian",
    "Simplified Chinese",
    "Traditional Chinese",
    "Czech",
    "Danish",
    "Dutch",
    "Finnish",
    "Greek",
    "Hungarian",
    "Indonesian",
    "Japanese",
    "Korean",
    "Norwegian",
    "Polish",
    "Portuguese - Portugal",
    "Portuguese - Brazil",
    "Romanian",
    "Russian",
    "Swedish",
    "Thai",
    "Turkish",
    "Ukrainian",
    "Vietnamese"
  ],
  "contentDescriptors": [
    "Fantasy Violence",
    "Violence",
    "Intense Violence",
    "Blood",
    "Blood and Gore",
    "Gore",
    "Mild Language",
    "Strong Language",
    "Sexual Content",
    "Sexual Themes",
    "Nudity",
    "Partial Nudity",
    "Mature Humor",
    "Crude Humor",
    "Drug Reference",
    "Use of Drugs",
    "Alcohol Reference",
    "Use of Alcohol",
    "Tobacco Reference",
    "Use of Tobacco",
    "Gambling",
    "Simulated Gambling",
    "In-Game Purchases",
    "Online Interactions",
    "User-Generated Content",
    "Horror",
    "Jump Scares",
    "Flashing Lights"
  ]
};
