import { useState, useEffect } from 'react';
import { useLocation } from 'wouter';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { useAuth } from '@/hooks/use-auth';
import { useToast } from '@/hooks/use-toast';
import { Loader2, ShieldCheck } from 'lucide-react';

const PENDING_OAUTH_REDIRECT_KEY = 'oauth_pending_redirect';

const SCOPE_LABELS: Record<string, string> = {
  'profile:read': 'View your public profile (username, display name, avatar, bio)',
  'profile:write': 'Update your public profile',
  'clips:read': 'View your clips',
  'clips:write': 'Post clips and screenshots on your behalf',
  'screenshots:read': 'View your screenshots',
  'screenshots:write': 'Post screenshots on your behalf',
  'games:read': 'View game data',
};

interface ClientInfo {
  name: string;
  description: string | null;
  logoUrl: string | null;
}

export default function OAuthAuthorizePage() {
  const [, setLocation] = useLocation();
  const { user, isLoading: authLoading } = useAuth();
  const { toast } = useToast();
  const [clientInfo, setClientInfo] = useState<ClientInfo | null>(null);
  const [isLoadingClient, setIsLoadingClient] = useState(true);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [errorMessage, setErrorMessage] = useState('');

  const params = new URLSearchParams(window.location.search);
  const clientId = params.get('client_id') || '';
  const redirectUri = params.get('redirect_uri') || '';
  const scope = params.get('scope') || '';
  const state = params.get('state') || '';
  // PKCE: the code_challenge is generated by the THIRD-PARTY app before it
  // redirects the user here — Gamefolio just forwards it through to
  // /oauth/token later, it never generates its own verifier/challenge.
  const codeChallenge = params.get('code_challenge') || '';
  const codeChallengeMethod = params.get('code_challenge_method') || '';
  const scopes = scope.split(' ').filter(Boolean);

  // Bounce unauthenticated users to login, then back here with the exact same
  // query string once they're signed in — there's no other returnTo mechanism
  // in the app, so this is stored in sessionStorage rather than app state.
  useEffect(() => {
    if (authLoading) return;
    if (!user) {
      try {
        sessionStorage.setItem(PENDING_OAUTH_REDIRECT_KEY, `/oauth/consent${window.location.search}`);
      } catch {}
      setLocation('/auth');
    }
  }, [user, authLoading, setLocation]);

  useEffect(() => {
    if (!clientId) {
      setErrorMessage('Missing client_id.');
      setIsLoadingClient(false);
      return;
    }
    fetch(`/api/oauth/client-info?client_id=${encodeURIComponent(clientId)}`)
      .then(async (res) => {
        if (!res.ok) throw new Error('unknown_client');
        return res.json();
      })
      .then((data: ClientInfo) => setClientInfo(data))
      .catch(() => setErrorMessage('This app is not registered or is no longer active.'))
      .finally(() => setIsLoadingClient(false));
  }, [clientId]);

  const handleDecision = async (decision: 'allow' | 'deny') => {
    setIsSubmitting(true);
    setErrorMessage('');
    try {
      const response = await fetch('/oauth/authorize/decision', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        credentials: 'include',
        body: JSON.stringify({
          clientId,
          redirectUri,
          scope,
          state,
          decision,
          codeChallenge,
          codeChallengeMethod,
        }),
      });

      const data = await response.json();
      if (!response.ok) {
        throw new Error(data.message || 'Something went wrong. Please try again.');
      }

      window.location.href = data.redirectUrl;
    } catch (error) {
      setIsSubmitting(false);
      toast({
        title: 'Error',
        description: error instanceof Error ? error.message : 'Something went wrong.',
        variant: 'gamefolioError',
      });
    }
  };

  if (authLoading || !user || isLoadingClient) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    );
  }

  if (errorMessage && !clientInfo) {
    return (
      <div className="min-h-screen flex items-center justify-center bg-background p-4">
        <Card className="w-full max-w-md">
          <CardHeader className="text-center">
            <CardTitle>Can't connect this app</CardTitle>
            <CardDescription>{errorMessage}</CardDescription>
          </CardHeader>
        </Card>
      </div>
    );
  }

  return (
    <div className="min-h-screen flex items-center justify-center bg-background p-4">
      <Card className="w-full max-w-md">
        <CardHeader className="text-center">
          <div className="mx-auto mb-4 flex items-center justify-center gap-3">
            {clientInfo?.logoUrl ? (
              <img src={clientInfo.logoUrl} alt={clientInfo.name} className="h-12 w-12 rounded-full object-cover" />
            ) : (
              <ShieldCheck className="h-12 w-12 text-primary" />
            )}
          </div>
          <CardTitle>{clientInfo?.name} wants to access your Gamefolio account</CardTitle>
          <CardDescription>Signed in as <strong>{user.username}</strong></CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-2">
            <p className="text-sm font-medium">This app will be able to:</p>
            <ul className="space-y-1.5">
              {scopes.map((s) => (
                <li key={s} className="text-sm text-muted-foreground flex items-start gap-2">
                  <ShieldCheck className="h-4 w-4 mt-0.5 shrink-0 text-primary" />
                  {SCOPE_LABELS[s] || s}
                </li>
              ))}
            </ul>
          </div>

          <div className="flex gap-3 pt-2">
            <Button
              variant="outline"
              className="flex-1"
              disabled={isSubmitting}
              onClick={() => handleDecision('deny')}
            >
              Deny
            </Button>
            <Button
              className="flex-1"
              disabled={isSubmitting}
              onClick={() => handleDecision('allow')}
            >
              {isSubmitting ? <Loader2 className="h-4 w-4 animate-spin" /> : 'Allow'}
            </Button>
          </div>

          <p className="text-xs text-muted-foreground text-center pt-2">
            You can revoke access at any time from Settings &gt; Connected Apps.
          </p>
        </CardContent>
      </Card>
    </div>
  );
}
