import { useState } from 'react';
import { createPortal } from 'react-dom';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useLocation, useSearch } from 'wouter';
import { ArrowLeft, Loader2, X, Users, AlertCircle, Lock } from 'lucide-react';
import CreateCampaignFlow from './CreateCampaignFlow';
import ConfirmedCampaignSetup from './ConfirmedCampaignSetup';
import { downloadCampaignContent } from '@/lib/campaign-content-download';
import { apiRequest } from '@/lib/queryClient';
import { CampaignContentGallery } from '@/components/bounties/CampaignContentGallery';
import { PackageReviewSection } from './MyCampaignsTab';
import { CampaignArtwork, StatusBadge, campaignDate, campaignCountdown } from './CampaignList';
import { campaignMetrics, COMPLETE_PARTICIPANTS, CAMPAIGN_ACTIONS, type ManagedCampaignStatus } from '@shared/campaign-management';
const button='inline-flex min-h-11 items-center justify-center gap-2 rounded-lg border border-[#394158] bg-[#151827] px-4 text-sm font-semibold text-white';
const field='min-h-11 rounded-lg border border-[#394158] bg-[#0F101B] px-3 py-2 text-sm text-white';
const tabs=['Setup','Progress','Creators','Submissions','Keys & Access','Timeline','Results'];
function creatorState(p:any,submissions:any[]){if(['expired','rejected'].includes(p.status))return 'Incomplete';if(p.status==='cancelled')return 'Removed';if(COMPLETE_PARTICIPANTS.includes(p.status))return 'Completed';if(p.status==='submitted_for_review')return 'Awaiting review';if(submissions.some(s=>Number(s.participant_id)===Number(p.user_id))||p.access_revealed_at)return 'Working';return 'Not started';}
function groups(objectives:any[],submissions:any[]){return objectives.map(o=>({...o,submissions:submissions.filter(s=>Number(s.bounty_id)===Number(o.id)).map(s=>({...s,media_url:s.video_url??s.image_url??s.content_url}))}));}
function ObjectiveProgress({objectives}:{objectives:any[]}){return <div className="space-y-4">{objectives.map(o=><div key={o.id} className="border-b border-[#303447] pb-4"><div className="flex flex-wrap justify-between gap-2"><h3 className="font-semibold">{o.title??o.content_type}</h3><span className="text-sm text-[#BAC0D0]">{o.expected ? `${o.approved} of ${o.expected} approved · ${o.percent}%` : 'No participants yet'}</span></div><p className="mt-1 text-xs text-[#BAC0D0]">{o.quantity} per creator · {o.submitted} submitted · {o.rejected} rejected</p>{o.expected > 0 && <progress value={o.approved} max={Math.max(1,o.expected)} aria-label={`${o.title??o.content_type} approved progress`} className="mt-2 h-2 w-full accent-[#B9FF1A]"/>}</div>)}</div>;}
export default function CampaignManagementDashboard({id,onBack,onEditDraft}:{id:number;onBack:()=>void;onEditDraft:(id:number)=>void}) {
  const client=useQueryClient(),[,navigate]=useLocation(),search=useSearch();
  const [tab,setTab]=useState(new URLSearchParams(search).get('campaignTab')??'Setup');
  const [searchCreator,setSearchCreator]=useState(''),[creatorFilter,setCreatorFilter]=useState('All creators'),[creator,setCreator]=useState<any>(null);
  const [submissionFilter,setSubmissionFilter]=useState('all'),[contentType,setContentType]=useState('all'),[contentCreator,setContentCreator]=useState('all');
  const [dialog,setDialog]=useState(new URLSearchParams(search).get('action')==='cancel'?'cancel':''),[reason,setReason]=useState(''),[confirm,setConfirm]=useState(false),[value,setValue]=useState('');
  const [saveRequest,setSaveRequest]=useState(0);
  const [error,setError]=useState(''),[busy,setBusy]=useState(false),[keys,setKeys]=useState(''),[keyPool,setKeyPool]=useState('access'),[keyType,setKeyType]=useState('full'),[revealedKey,setRevealedKey]=useState('');
  const query=useQuery<any>({queryKey:['campaign-dashboard',id],queryFn:async()=>(await apiRequest('GET',`/api/campaigns/instances/${id}/dashboard`)).json(),refetchInterval:10000});
  async function refresh(){await client.invalidateQueries({queryKey:['campaign-dashboard',id]});await client.invalidateQueries({queryKey:['/api/campaigns/management']});}
  async function manage(action:string,extra:any={}){setBusy(true);setError('');try{const result=await(await apiRequest('POST',`/api/campaigns/instances/${id}/manage`,{action,...extra})).json();await refresh();setDialog('');setValue('');if(action==='duplicate')onEditDraft(result.id);}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  async function addKeys(){setBusy(true);setError('');try{await apiRequest('POST',`/api/campaigns/instances/${id}/keys`,{keyType,keyPool,keys:keys.split(/\r?\n/).map(k=>k.trim()).filter(Boolean)});setKeys('');setDialog('');await refresh();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
  const switchTab=(next:string)=>{setTab(next);const params=new URLSearchParams(search);params.set('campaignTab',next);params.delete('action');navigate(`/game-dashboard?${params}`,{replace:true});};
  if(query.isLoading)return <div className="flex justify-center py-20"><Loader2 className="animate-spin text-[#B9FF1A]"/></div>;
  if(query.isError||!query.data)return <section className="rounded-xl bg-[#151827] p-8"><h1 className="text-xl font-bold">We couldn’t load this campaign</h1><button onClick={()=>query.refetch()} className={`${button} mt-4`}>Retry</button></section>;
  const data=query.data,c=data.campaign,m=data.metrics,readOnly=['completed','cancelled'].includes(c.status),active=['scheduled','live'].includes(c.status);
  const allowed = c.status==='scheduled'?['Setup','Keys & Access','Timeline']:c.status==='cancelled'?['Setup','Timeline',...(m.contentReceived||m.creatorsJoined?['Results']:[])]:c.status==='payment_processing'?['Setup']:['Setup','Progress','Creators','Submissions','Keys & Access','Timeline',...(['under_review','completed'].includes(c.status)?['Results']:[])];
  const availableTabs=tabs.filter(t=>allowed.includes(t));
  const currentTab=availableTabs.includes(tab==='Overview'?'Progress':tab)?(tab==='Overview'?'Progress':tab):'Setup';
  const participants=data.participants.filter((p:any)=>(p.username??p.display_name??'').toLowerCase().includes(searchCreator.toLowerCase())&&(creatorFilter==='All creators'||creatorState(p,data.submissions)===creatorFilter));
  const submissions=data.submissions.filter((s:any)=>(submissionFilter==='all'||s.status===submissionFilter)&&(contentType==='all'||s.content_type===contentType)&&(contentCreator==='all'||String(s.participant_id)===contentCreator));
  const creatorSubs=creator?data.submissions.filter((s:any)=>Number(s.participant_id)===Number(creator.user_id)):[];
  const creatorMetrics=creator?campaignMetrics(c,[creator],creatorSubs,data.keys.filter((k:any)=>Number(k.assigned_user_id)===Number(creator.user_id)),data.rewards.filter((r:any)=>Number(r.participant_id)===Number(creator.id)),data.objectives):null;
  if(c.status==='draft')return <section className="space-y-6"><button onClick={onBack} className={button}><ArrowLeft size={17}/>My Campaigns</button><nav className="border-b border-[#303447]"><span className="inline-flex min-h-11 items-center border-b-2 border-[#B9FF1A] px-4 text-sm font-semibold text-[#B9FF1A]">Setup</span></nav><CreateCampaignFlow editInstanceId={id} onComplete={onBack}/></section>;
  return <section className="space-y-6 bg-[#0F101B] font-['Space_Grotesk'] text-white">
    <button onClick={onBack} className={button}><ArrowLeft size={17}/>My Campaigns</button>
    <header className="rounded-xl border border-[#303447] bg-[#151827] p-5"><div className="flex flex-wrap gap-4"><CampaignArtwork campaign={c} className="h-24 w-24"/><div className="min-w-0 flex-1"><p className="text-sm text-[#BAC0D0]">{c.game_name} · {c.template_name} · Campaign #{id}</p><h1 className="my-2 break-words text-2xl font-bold">{c.campaign_title||c.template_name}</h1><StatusBadge status={c.status}/><p className="mt-3 text-sm text-[#BAC0D0]">Start: {campaignDate(c.actual_start??c.scheduled_start)} · End: {campaignDate(c.end_date)}</p>{c.status==='scheduled'?<p className="mt-1 text-sm">Launches in {campaignCountdown(c.actual_start??c.scheduled_start)}</p>:['live','in_progress'].includes(c.status)&&<p className="mt-1 text-sm">{campaignCountdown(c.end_date)} remaining · {m.placesAvailable} places available</p>}</div><div className="flex flex-wrap items-start gap-2">{c.status==='draft'?<button className={button} onClick={()=>onEditDraft(id)}>Continue Setup</button>:c.status==='payment_processing'?<button className={button} onClick={()=>navigate(`/game-dashboard?tab=campaigns&campaignPayment=${id}`)}>Confirming your payment…</button>:<button className={`${button} text-[#B9FF1A]`} onClick={()=>{if(['scheduled','live'].includes(c.status)){switchTab('Setup');setSaveRequest(n=>n+1);}else if(c.status==='cancelled')void manage('duplicate');else switchTab(c.status==='under_review'?'Submissions':'Results');}}>{['scheduled','live'].includes(c.status)?'Save Changes':c.status==='cancelled'?'Duplicate Campaign':CAMPAIGN_ACTIONS[c.status as ManagedCampaignStatus]}</button>}{['scheduled','live'].includes(c.status)&&<a className={button} href={`/bounties?campaign=${id}`}>Preview Public Campaign</a>}<a className={button} href={`/api/campaigns/instances/${id}/report`}>Export report</a></div></div>
      {c.payment_error&&<p role="alert" className="mt-4 text-amber-300">{c.payment_error}</p>}{readOnly&&<p className="mt-4 flex items-center gap-2 text-sm text-[#BAC0D0]"><Lock size={15}/>This campaign’s history and results are read-only.</p>}{c.cancellation_reason&&<p className="mt-2 text-sm text-[#BAC0D0]">Cancellation: {c.cancellation_reason}</p>}
    </header>
    <nav className="flex overflow-x-auto border-b border-[#303447]" aria-label="Campaign dashboard tabs">{availableTabs.map(t=><button key={t} onClick={()=>switchTab(t)} className={`min-h-11 shrink-0 border-b-2 px-4 text-sm font-semibold ${currentTab===t?'border-[#B9FF1A] text-[#B9FF1A]':'border-transparent text-[#BAC0D0]'}`}>{t}</button>)}</nav>
    {error&&<p role="alert" className="text-amber-300">{error}</p>}
    <div className="text-sm text-[#D2D6E0]" role="status">{c.status==='scheduled'?<>Campaign scheduled. This campaign has been confirmed and will go live automatically on {campaignDate(c.actual_start??c.scheduled_start)}.</>:c.status==='live'?<>Campaign live · {m.creatorsJoined} creators participating. Creators can now discover and join this campaign. Some details are locked to protect creators already taking part.</>:c.status==='completed'?'Campaign completed. This campaign has finished. Its settings and results are preserved as a permanent record.':c.status==='cancelled'?<>Cancelled {campaignDate(c.cancelled_at)} · {c.cancellation_reason}. Refund status: contact Gamefolio Support for policy and eligibility.</>:c.status==='under_review'?<>Campaign under review · {m.pendingReviews} submissions awaiting review · {data.participants.filter((p:any)=>p.status==='submitted_for_review').length} creators awaiting approval · {m.pendingRewards} rewards awaiting distribution.</>:'Confirming your payment…'}</div>
    <div hidden={currentTab!=='Setup'}><ConfirmedCampaignSetup data={data} onSaved={refresh} saveRequest={saveRequest} onManage={action=>{if(action==='resume')void manage(action);else {setDialog(action);setValue(action==='places'?String(Number(c.max_places)+1):'');}}} onKeys={()=>switchTab('Keys & Access')}/></div>
    {currentTab==='Progress'&&<>
      {c.status==='under_review'&&<div className="rounded-xl border border-[#394158] bg-[#151827] p-5"><h2 className="font-semibold">Campaign review</h2><p className="mt-2 text-sm text-[#D2D6E0]">{m.pendingReviews} pending submissions · {m.contentApproved} approved · {m.contentRejected} rejected · {data.participants.filter((p:any)=>p.status==='submitted_for_review').length} creators awaiting approval · {m.pendingRewards} rewards pending</p><button className={`${button} mt-3 text-[#B9FF1A]`} onClick={()=>switchTab('Submissions')}>Review Submissions</button></div>}
      <div className="grid grid-cols-2 gap-4 md:grid-cols-3 xl:grid-cols-5">{[['Creators joined',m.creatorsJoined],['Actively working',m.creatorsActive],['Creators completed',m.creatorsCompleted],['Overall completion',`${m.completionPercent}%`],['Content received',m.contentReceived],['Content approved',m.contentApproved],['Pending reviews',m.pendingReviews],['Keys allocated',m.keysAllocated],['Keys issued',m.keysIssued],['XP distributed',m.xpDistributed.toLocaleString()]].map(([label,value])=><div key={label} className="rounded-xl bg-[#151827] p-4"><p className="text-xs text-[#BAC0D0]">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>)}</div>
      <div className="rounded-xl bg-[#151827] p-5"><h2 className="mb-4 text-lg font-bold">Objective progress</h2><ObjectiveProgress objectives={m.objectives}/>{!m.creatorsJoined&&<div className="mt-4"><h3 className="font-semibold">Waiting for creators</h3><p className="mt-1 text-sm text-[#BAC0D0]">{c.status==='scheduled'?'Creators can join when the campaign goes live.':'Creator activity will appear here when someone joins.'}</p></div>}</div>
      {active&&<div className="flex flex-wrap gap-3"><button className={button} onClick={()=>c.applications_paused?manage('resume'):setDialog('pause')} disabled={busy||c.status==='under_review'}>{c.applications_paused?'Resume applications':'Pause new applications'}</button><button className={button} onClick={()=>{setDialog('extend');setValue('');}}>Extend deadline</button><button className={button} onClick={()=>{setDialog('places');setValue(String(Number(c.max_places)+1));}}>Add creator places</button><button className={button} onClick={()=>{setDialog('clarification');setValue('');}}>Add clarification / FAQ</button><button className={button} onClick={()=>setDialog('cancel')}>Cancel campaign</button><a className={button} href="/help">Contact Support</a></div>}
      {data.timeline.filter((e:any)=>e.type==='clarification_added').map((e:any,i:number)=><div key={i} className="rounded-xl bg-[#151827] p-4"><h3 className="font-semibold">Campaign clarification</h3><p className="mt-2 whitespace-pre-wrap text-sm text-[#D2D6E0]">{e.detail}</p></div>)}
    </>}
    {currentTab==='Creators'&&<div className="space-y-4"><div className="flex flex-wrap gap-3"><input aria-label="Search creators" placeholder="Search creators" value={searchCreator} onChange={e=>setSearchCreator(e.target.value)} className={`${field} max-w-full`}/><select aria-label="Filter creators" value={creatorFilter} onChange={e=>setCreatorFilter(e.target.value)} className={field}>{['All creators','Not started','Working','Awaiting review','Completed','Incomplete','Removed'].map(f=><option key={f}>{f}</option>)}</select></div>
      {!participants.length?<Empty title="Waiting for creators" text="Creator activity will appear here when someone joins."/>:<div className="overflow-x-auto rounded-xl bg-[#151827]"><table className="w-full text-left text-sm"><thead className="text-xs text-[#BAC0D0]"><tr>{['Creator','Joined','Access / key','Objectives','Submissions','Approval','Reward','Last activity','Progress'].map(h=><th key={h} className="p-3">{h}</th>)}</tr></thead><tbody>{participants.map((p:any)=>{const work=data.submissions.filter((s:any)=>Number(s.participant_id)===Number(p.user_id)),reward=data.rewards.filter((r:any)=>Number(r.participant_id)===Number(p.id)),metric=campaignMetrics(c,[p],work,[],reward,data.objectives);return <tr key={p.id} className="border-t border-[#303447]"><td className="p-3"><button onClick={()=>setCreator(p)} className="flex min-h-11 items-center gap-2 text-[#B9FF1A]">{p.avatar_url?<img src={p.avatar_url} alt="" className="h-8 w-8 rounded-full"/>:<Users size={22}/>}@{p.username}</button></td><td className="p-3 whitespace-nowrap">{campaignDate(p.joined_at)}</td><td className="p-3">{p.access_revealed_at?'Key revealed':p.access_key_id?'Key allocated':'Keyless access'}</td><td className="p-3">{metric.approvedUnits}/{metric.expectedUnits}</td><td className="p-3">{work.length}</td><td className="p-3">{creatorState(p,work)}</td><td className="p-3">{reward.length?reward.every((r:any)=>r.status==='awarded')?'Distributed':'Pending':'Not earned'}</td><td className="p-3 whitespace-nowrap">{campaignDate(work[0]?.reviewed_at??work[0]?.submitted_at??p.access_revealed_at??p.joined_at)}</td><td className="p-3">{metric.completionPercent}%</td></tr>;})}</tbody></table></div>}
    </div>}
    {currentTab==='Submissions'&&<div className="space-y-5"><div className="flex flex-wrap gap-3"><select aria-label="Submission status" value={submissionFilter} onChange={e=>setSubmissionFilter(e.target.value)} className={field}>{[['all','All submissions'],['under_review','Pending review'],['approved','Approved'],['changes_requested','Changes requested'],['rejected','Rejected'],['pending','Staged / pending']].map(([id,label])=><option key={id} value={id}>{label}</option>)}</select><select aria-label="Content type" value={contentType} onChange={e=>setContentType(e.target.value)} className={field}><option value="all">All content types</option>{Array.from(new Set<string>(data.submissions.map((s:any)=>s.content_type))).map(type=><option key={type}>{type}</option>)}</select><select aria-label="Content creator" value={contentCreator} onChange={e=>setContentCreator(e.target.value)} className={field}><option value="all">All creators</option>{data.participants.map((p:any)=><option key={p.user_id} value={p.user_id}>@{p.username}</option>)}</select></div>
      {!submissions.length?<Empty title="No submissions yet" text="Content will appear here as creators complete their campaign objectives."/>:<>{data.participants.filter((p:any)=>submissions.some((s:any)=>Number(s.participant_id)===Number(p.user_id))).map((p:any)=><section key={p.id} className="rounded-xl bg-[#151827] p-5"><div className="mb-4 flex flex-wrap items-center justify-between gap-2"><button onClick={()=>setCreator(p)} className={`${button} text-[#B9FF1A]`}>@{p.username} · View creator progress</button><span className="text-xs text-[#BAC0D0]">{submissions.filter((s:any)=>Number(s.participant_id)===Number(p.user_id)).length} submissions</span></div><CampaignContentGallery objectives={groups(data.objectives,submissions.filter((s:any)=>Number(s.participant_id)===Number(p.user_id)))} state="locked" gameName={c.game_name}/><div className="mt-3 flex flex-wrap gap-3">{submissions.filter((s:any)=>Number(s.participant_id)===Number(p.user_id)).map((s:any)=>{const url=s.video_url??s.image_url??s.content_url;return <div key={s.id} className="text-xs text-[#BAC0D0]">{s.content_type} · {campaignDate(s.submitted_at)} · {s.status}{s.views!=null&&` · ${s.views} views`}{url&&<a href={url} target="_blank" rel="noreferrer" download className="ml-2 inline-flex min-h-11 items-center text-[#B9FF1A] underline">Open / download</a>}{s.clip_id&&<button className="ml-2 min-h-11 text-[#B9FF1A] underline" onClick={()=>navigator.clipboard.writeText(`${window.location.origin}/clip/${s.clip_id}`)}>Copy public link</button>}</div>;})}</div></section>)}</>}
      <PackageReviewSection instanceId={id} readOnly={readOnly}/>
    </div>}
    {currentTab==='Keys & Access'&&<div className="space-y-5"><div className="rounded-xl bg-[#151827] p-5"><h2 className="text-lg font-semibold">{c.access_method?.replace(/_/g,' ')}</h2><p className="mt-2 text-sm text-[#BAC0D0]">{c.access_method==='demo_to_full'?'Demo access at joining; full-game access after approved completion.':c.requires_access_key===false?'Creators participate without a supplied key.':'Keys are allocated to each creator securely.'}</p><dl className="mt-5 grid grid-cols-2 gap-4 md:grid-cols-4">{[['Allocated',m.keysAllocated],['Available',m.keysAvailable],['Reserved',m.keysReserved],['Distributed',m.keysIssued],['Revealed',m.keysRevealed],['Removed',m.keysRevoked],['Full keys awaiting unlock',m.fullKeysWaiting]].map(([label,value])=><div key={label}><dt className="text-xs text-[#BAC0D0]">{label}</dt><dd className="mt-1 text-xl font-semibold">{value}</dd></div>)}</dl></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead><tr>{['Key ID','Type','Pool','Status','Creator','Issued','Revealed'].map(h=><th key={h} className="p-3 text-[#BAC0D0]">{h}</th>)}</tr></thead><tbody>{data.keys.map((k:any)=><tr key={k.id} className="border-t border-[#303447]"><td className="p-3">#{k.id}</td><td className="p-3">{k.key_type}</td><td className="p-3">{k.key_pool}</td><td className="p-3">{k.status}</td><td className="p-3">{data.participants.find((p:any)=>Number(p.user_id)===Number(k.assigned_user_id))?.username??'Unassigned'}</td><td className="p-3">{campaignDate(k.assigned_at)}</td><td className="p-3">{campaignDate(k.revealed_at)}{k.assigned_user_id&&!k.removed_at&&<button className="ml-2 min-h-11 text-[#B9FF1A] underline" onClick={async()=>{try{const result=await(await apiRequest('POST',`/api/campaigns/instances/${id}/keys/${k.id}/reveal`,{})).json();setRevealedKey(result.key);}catch(e:any){setError(e.message);}}}>Reveal key</button>}</td></tr>)}</tbody></table></div>{active&&<form onSubmit={e=>{e.preventDefault();setDialog('keys');}} className="rounded-xl bg-[#151827] p-5"><h3 className="font-semibold">Add more game keys</h3><div className="mt-3 flex flex-wrap gap-3"><select aria-label="Key type" className={field} value={keyType} onChange={e=>setKeyType(e.target.value)}><option value="full">Full-game keys</option><option value="demo">Demo / playtest keys</option></select><select aria-label="Key pool" className={field} value={keyPool} onChange={e=>setKeyPool(e.target.value)}><option value="access">Joining access</option><option value="reward">Completion reward</option></select></div><textarea aria-label="Game keys, one per line" className={`${field} mt-3 w-full`} rows={4} value={keys} onChange={e=>setKeys(e.target.value)} placeholder="Paste game keys, one per line" spellCheck={false}/><button disabled={busy||!keys.trim()} className={`${button} mt-3`}>Add keys</button></form>}</div>}
    {currentTab==='Timeline'&&<ol className="rounded-xl bg-[#151827] p-5">{data.timeline.map((e:any,i:number)=><li key={i} className="border-b border-[#303447] py-4"><div className="flex flex-wrap justify-between gap-2"><strong className="text-sm">{e.type.replace(/_/g,' ')}</strong><time className="text-xs text-[#BAC0D0]">{campaignDate(e.at)}</time></div><p className="mt-1 text-xs text-[#BAC0D0]">{e.actor??'System'}{e.detail&&` · ${e.detail}`}</p></li>)}</ol>}
    {currentTab==='Results'&&<div className="space-y-5"><h2 className="text-xl font-bold">{c.status==='completed'?'Final campaign results':'Campaign results so far'}</h2><div className="grid grid-cols-2 gap-4 md:grid-cols-4">{[['Creators joined',m.creatorsJoined],['Creators completed',m.creatorsCompleted],['Completion rate',m.creatorsJoined?`${Math.round(m.creatorsCompleted/m.creatorsJoined*100)}%`:'0%'],['Submitted content',m.contentReceived],['Approved',m.contentApproved],['Rejected',m.contentRejected],['Verified streams',m.verifiedStreams],['Keys distributed',m.keysIssued],['XP awarded',m.xpDistributed],['Campaign spend',c.amount_paid!=null?`£${(Number(c.amount_paid)/100).toFixed(2)}`:c.commercial_type==='starter'?'Included with Pro':'Unpaid'],['Content views',data.submissions.reduce((sum:number,s:any)=>sum+Number(s.views??0),0)],['Duration',c.actual_start&&c.end_date?`${Math.ceil((new Date(c.end_date).getTime()-new Date(c.actual_start).getTime())/86400000)} days`:'Not started']].map(([label,value])=><div key={label} className="rounded-xl bg-[#151827] p-4"><p className="text-xs text-[#BAC0D0]">{label}</p><p className="mt-2 text-xl font-semibold">{value}</p></div>)}</div><div className="rounded-xl bg-[#151827] p-5"><ObjectiveProgress objectives={m.objectives}/></div><div className="flex flex-wrap gap-3"><button className={button} onClick={()=>switchTab('Submissions')}>View All Content</button><button className={button} disabled={busy||!m.contentApproved} onClick={async()=>{setBusy(true);setError('');try{await downloadCampaignContent(id,data.submissions);}catch(e:any){setError(e.message);}finally{setBusy(false);}}}>{busy?'Preparing download…':'Download Approved Content'}</button><a className={button} href={`/api/campaigns/instances/${id}/report`}>Export Campaign Report</a><a className={button} href={`/api/campaigns/instances/${id}/report?kind=feedback`}>Export Creator Feedback</a><button className={button} disabled={busy} onClick={()=>manage('duplicate')}>Duplicate Campaign</button><button className={button} disabled={busy} onClick={()=>manage('duplicate')}>Run Campaign Again</button></div>{c.payment_reference&&<p className="text-xs text-[#BAC0D0]">Payment reference: {c.payment_reference}</p>}</div>}
    {revealedKey&&createPortal(<div className="fixed inset-0 z-[110] flex items-center justify-center bg-black/75 p-4"><section role="dialog" aria-modal="true" aria-label="Distributed key" className="w-full max-w-lg rounded-xl bg-[#151827] p-6 text-white"><h2 className="text-lg font-bold">Distributed game key</h2><code className="my-4 block break-all rounded-lg bg-[#0F101B] p-4">{revealedKey}</code><button className={button} onClick={()=>setRevealedKey('')}>Close</button></section></div>,document.body)}
    {creator&&createPortal(<div className="fixed inset-0 z-[100] flex justify-end bg-black/70" onClick={()=>setCreator(null)}><aside role="dialog" aria-modal="true" aria-label="Creator progress" className="h-full w-full max-w-2xl overflow-y-auto bg-[#151827] p-5 text-white" onClick={e=>e.stopPropagation()}><button className={`${button} float-right`} onClick={()=>setCreator(null)} aria-label="Close creator progress"><X size={18}/></button><h2 className="text-xl font-bold">@{creator.username}</h2><p className="my-4 text-sm text-[#BAC0D0]">Joined {campaignDate(creator.joined_at)} · {creatorState(creator,creatorSubs)} · {creatorMetrics?.completionPercent}%</p><ObjectiveProgress objectives={creatorMetrics?.objectives??[]}/><CampaignContentGallery objectives={groups(data.objectives,creatorSubs)} state="locked" gameName={c.game_name}/><h3 className="mt-5 font-semibold">Key history</h3>{data.keys.filter((k:any)=>Number(k.assigned_user_id)===Number(creator.user_id)).map((k:any)=><p key={k.id} className="mt-2 text-sm">#{k.id} · {k.key_type} · {k.status} · {campaignDate(k.assigned_at)}</p>)}<h3 className="mt-5 font-semibold">Reward history</h3>{data.rewards.filter((r:any)=>Number(r.participant_id)===Number(creator.id)).map((r:any)=><p key={r.id} className="mt-2 text-sm">{r.amount??0} XP · {r.status} · {campaignDate(r.updated_at)}</p>)}</aside></div>,document.body)}
    {dialog&&createPortal(<div className="fixed inset-0 z-[110] flex items-center justify-center bg-black/75 p-4"><section role="dialog" aria-modal="true" aria-label="Manage campaign" className="w-full max-w-lg rounded-xl border border-[#394158] bg-[#151827] p-6 text-white"><h2 className="text-xl font-bold">{dialog==='cancel'?data.can_cancel?'Cancel this campaign?':'Campaign cannot be cancelled':dialog==='extend'?'Extend campaign deadline':dialog==='places'?'Add creator places':dialog==='pause'?'Pause new applications?':dialog==='keys'?'Allocate additional game keys?':'Add a clarification'}</h2>
      {dialog==='cancel'?data.can_cancel?<><p className="mt-3 text-sm text-[#D2D6E0]">This will remove the campaign from the Bounty Hub and prevent creators from joining. The campaign record will remain available in My Campaigns.</p><textarea aria-label="Cancellation reason" value={reason} onChange={e=>setReason(e.target.value)} maxLength={2000} placeholder="Cancellation reason" className={`${field} mt-4 w-full`} rows={3}/><label className="mt-3 flex min-h-11 items-center gap-2 text-sm"><input type="checkbox" checked={confirm} onChange={e=>setConfirm(e.target.checked)}/>I understand the campaign will stop accepting creators.</label></>:<><p className="mt-3 text-sm text-[#D2D6E0]">This campaign has active creator work, distributed access or submitted content. Contact Gamefolio Support if you need help.</p><a href="/help" className={`${button} mt-4`}>Contact Support</a></>:dialog==='pause'?<p className="mt-4 text-sm text-[#D2D6E0]">New creators will be unable to join. Existing creator work and rewards will be preserved.</p>:dialog==='keys'?<p className="mt-4 text-sm text-[#D2D6E0]">These additional keys will be added to this campaign’s inventory. Issued keys and the accepted access method will remain unchanged.</p>:dialog==='clarification'?<textarea aria-label="Clarification" className={`${field} mt-4 w-full`} value={value} onChange={e=>setValue(e.target.value)} maxLength={4000} rows={4}/>:<input aria-label={dialog==='extend'?'New deadline':'Total creator places'} className={`${field} mt-4 w-full`} type={dialog==='extend'?'datetime-local':'number'} min={dialog==='places'?Number(c.max_places)+1:undefined} max={dialog==='places'?100:undefined} value={value} onChange={e=>setValue(e.target.value)}/>}
      {error&&<p role="alert" className="mt-3 text-amber-300">{error}</p>}<div className="mt-5 flex flex-wrap gap-3"><button className={button} onClick={()=>{setDialog('');setError('');}}>{dialog==='cancel'?'Keep Campaign Live':'Cancel'}</button>{(dialog!=='cancel'||data.can_cancel)&&<button disabled={busy||(dialog==='cancel'? !confirm||!reason.trim():!['pause','keys'].includes(dialog)&&!value.trim())} className={`${button} ${dialog==='cancel'?'border-red-400 text-red-300':'text-[#B9FF1A]'}`} onClick={()=>dialog==='keys'?addKeys():manage(dialog,dialog==='cancel'?{reason,confirm}:dialog==='extend'?{endDate:new Date(value).toISOString()}:dialog==='places'?{places:Number(value)}:{text:value})}>{busy?'Saving…':dialog==='cancel'?'Cancel Campaign':'Save change'}</button>}</div></section></div>,document.body)}
  </section>;
}
function Empty({title,text}:{title:string;text:string}){return <div className="rounded-xl bg-[#151827] p-8 text-center"><h2 className="text-lg font-semibold">{title}</h2><p className="mt-2 text-sm text-[#BAC0D0]">{text}</p></div>;}
