import { useState } from 'react';
import { useQuery, useQueryClient } from '@tanstack/react-query';
import { useLocation } from 'wouter';
import { Plus, MoreHorizontal, Gamepad2, ArrowRight, Loader2 } from 'lucide-react';
import { apiRequest } from '@/lib/queryClient';
import { useSignedUrl } from '@/hooks/use-signed-url';
import { CAMPAIGN_STATUSES, CAMPAIGN_STATUS_LABELS, CAMPAIGN_ACTIONS, type ManagedCampaignStatus } from '@shared/campaign-management';
export function CampaignArtwork({campaign,className='h-16 w-16'}:{campaign:any;className?:string}) {
  const {signedUrl}=useSignedUrl(campaign.hero_artwork_url??campaign.game_artwork_url??campaign.artwork_url);
  const [failed,setFailed]=useState(false);
  return <div className={`relative shrink-0 overflow-hidden rounded-lg bg-[#0F101B] ${className}`}><Gamepad2 className="absolute inset-0 m-auto text-[#B9FF1A]" size={26}/>{signedUrl&&!failed&&<img src={signedUrl} alt="" onError={()=>setFailed(true)} className="relative h-full w-full object-cover"/>}</div>;
}
export function StatusBadge({status}:{status:ManagedCampaignStatus}){return <span className="inline-flex rounded border border-[#394158] px-2 py-1 text-xs font-semibold" style={{color:['live','completed'].includes(status)?'#B9FF1A':status==='under_review'?'#FBBF24':'#D2D6E0'}}>{CAMPAIGN_STATUS_LABELS[status]}</span>;}
export function campaignDate(date:any){return date?new Date(date).toLocaleString(undefined,{dateStyle:'medium',timeStyle:'short'}):'Not set';}
export function campaignCountdown(date:any){if(!date)return 'Not scheduled';const hours=Math.max(0,Math.ceil((new Date(date).getTime()-Date.now())/3600000));return hours>=24?`${Math.ceil(hours/24)} days`:`${hours} hours`;}
export default function CampaignList({onCreateCampaign,onEditDraft,gameId}:{onCreateCampaign:()=>void;onEditDraft:(id:number)=>void;gameId?:number}) {
  const [,navigate]=useLocation(),client=useQueryClient();
  const [filter,setFilter]=useState('all'),[archived,setArchived]=useState(false),[error,setError]=useState('');
  const query=useQuery<any[]>({queryKey:['/api/campaigns/management'],queryFn:async()=> (await apiRequest('GET','/api/campaigns/management')).json(),refetchInterval:15000});
  const campaigns=(query.data??[]).filter(c=>!gameId||Number(c.profile_game_id)===gameId);
  const visible=campaigns.filter(c=>archived?!!c.archived_at:!c.archived_at),filtered=filter==='all'?visible:visible.filter(c=>c.status===filter);
  const open=(c:any)=>c.status==='draft'?onEditDraft(c.id):c.status==='payment_processing'?navigate(`/game-dashboard?tab=campaigns&campaignPayment=${c.id}`):navigate(`/game-dashboard?tab=campaigns&viewCampaign=${c.id}`);
  const manage=async(c:any,action:string)=>{setError('');try{const result=await(await apiRequest('POST',`/api/campaigns/instances/${c.id}/manage`,{action})).json();await client.invalidateQueries({queryKey:['/api/campaigns/management']});if(action==='duplicate')onEditDraft(result.id);}catch(e:any){setError(e.message);}};
  if(query.isLoading)return <div className="flex justify-center py-20"><Loader2 className="animate-spin text-[#B9FF1A]"/></div>;
  if(query.isError)return <div className="rounded-xl bg-[#151827] p-6"><h2 className="font-bold">We couldn’t load your campaigns</h2><button onClick={()=>query.refetch()} className="mt-4 min-h-11 rounded-lg border border-white/20 px-5">Retry</button></div>;
  return <section className="space-y-5 font-['Space_Grotesk'] text-white">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">My Campaigns</h1><p className="mt-1 text-sm text-[#BAC0D0]">Manage creator activity, submissions and campaign results.</p></div><button onClick={onCreateCampaign} className="flex min-h-11 items-center gap-2 rounded-lg bg-[#B9FF1A] px-4 font-semibold text-[#0F101B]"><Plus size={18}/>New Campaign</button></div>
    <div className="flex flex-wrap gap-2">{['all',...CAMPAIGN_STATUSES.filter(s=>s!=='payment_processing')].map(s=><button key={s} onClick={()=>setFilter(s)} className={`min-h-11 rounded-lg border bg-[#151827] px-3 text-sm ${filter===s?'border-[#B9FF1A] text-[#B9FF1A]':'border-[#303447] text-[#D2D6E0]'}`}>{s==='all'?'All':s==='draft'?'Drafts':CAMPAIGN_STATUS_LABELS[s as ManagedCampaignStatus]} <span className="ml-1 text-xs">{s==='all'?visible.length:visible.filter(c=>c.status===s).length}</span></button>)}<button onClick={()=>setArchived(!archived)} className="min-h-11 px-3 text-sm text-[#BAC0D0] underline">{archived?'Show current':'Show archived'}</button></div>
    {error&&<p role="alert" className="text-amber-300">{error}</p>}
    {!filtered.length?<div className="rounded-xl border border-[#303447] bg-[#151827] p-10 text-center"><h2 className="text-lg font-semibold">{campaigns.length===0?'Create your first campaign':filter==='completed'?'No completed campaigns yet':'No campaigns in this view'}</h2><p className="mt-2 text-[#BAC0D0]">{campaigns.length===0?'Reach creators, generate content and collect useful feedback for your game.':filter==='completed'?'Your finished campaigns and final reports will appear here.':'Choose another status or view archived campaigns.'}</p></div>:<div className="grid gap-4 lg:grid-cols-2 xl:grid-cols-3">{filtered.map(c=>{
      const m=c.metrics;return <article key={c.id} className="relative rounded-xl border border-[#303447] bg-[#151827] p-5 hover:border-[#68728A]">
        <button aria-label={`Open ${c.campaign_title??c.template_name}`} onClick={()=>open(c)} className="absolute inset-0 z-0 rounded-xl focus-visible:ring-2 focus-visible:ring-[#B9FF1A]"/>
        <div className="pointer-events-none relative flex gap-3"><CampaignArtwork campaign={c}/><div className="min-w-0"><h2 className="truncate text-base font-bold">{c.campaign_title||c.template_name}</h2><p className="mb-2 text-sm text-[#BAC0D0]">{c.template_name}</p><StatusBadge status={c.status}/></div></div>
        <dl className="pointer-events-none relative mt-5 grid grid-cols-2 gap-x-4 gap-y-3 text-sm">{[['Creators',`${m.creatorsJoined} / ${c.max_places??'—'}`],['Completion',`${m.completionPercent}%`],['Content received',m.contentReceived],['Pending approvals',m.pendingReviews],['XP allocated',c.bounty_xp_reward==null||c.max_places==null?'Not configured':`${(Number(c.bounty_xp_reward)*Number(c.max_places??0)).toLocaleString()}`],['Places available',m.placesAvailable]].map(([label,value])=><div key={label}><dt className="text-xs text-[#BAC0D0]">{label}</dt><dd className="mt-1 font-semibold">{value}</dd></div>)}</dl>
        <div className="pointer-events-none relative mt-4 space-y-1 text-xs text-[#BAC0D0]"><p>Start: {campaignDate(c.actual_start??c.scheduled_start)}</p><p>End: {campaignDate(c.end_date)}</p>{['live'].includes(c.status)&&<p>{campaignCountdown(c.end_date)} remaining</p>}{c.status==='scheduled'&&<p>Launches in {campaignCountdown(c.actual_start??c.scheduled_start)}</p>}{(c.payment_error||c.payment_status==='payment_failed')&&<p className="text-amber-300">{c.payment_error||'Payment failed. Your draft is saved; continue setup to try again.'}</p>}</div>
        <div className="relative mt-4 flex items-center justify-between border-t border-[#303447] pt-3"><button onClick={()=>open(c)} className="flex min-h-11 items-center gap-2 text-sm font-semibold text-[#B9FF1A]">{CAMPAIGN_ACTIONS[c.status as ManagedCampaignStatus]}<ArrowRight size={16}/></button><details className="relative"><summary aria-label="Campaign actions" className="flex min-h-11 min-w-11 cursor-pointer list-none items-center justify-center rounded-lg border border-[#303447]"><MoreHorizontal size={20}/></summary><div className="absolute bottom-12 right-0 z-20 w-48 rounded-xl border border-[#394158] bg-[#0F101B] p-2 shadow-xl"><button onClick={()=>manage(c,'duplicate')} className="min-h-11 w-full px-2 text-left text-sm">Duplicate campaign</button><a href={`/api/campaigns/instances/${c.id}/report`} className="flex min-h-11 items-center px-2 text-sm">Export report</a><button onClick={()=>manage(c,'archive')} className="min-h-11 w-full px-2 text-left text-sm">{c.archived_at?'Unarchive':'Archive'}</button>{c.can_cancel&&<button onClick={()=>navigate(`/game-dashboard?tab=campaigns&viewCampaign=${c.id}&action=cancel`)} className="min-h-11 w-full px-2 text-left text-sm text-red-300">Cancel campaign</button>}{c.status==='draft'&&<button onClick={()=>{if(window.confirm('Delete this unpaid draft?'))manage(c,'delete');}} className="min-h-11 w-full px-2 text-left text-sm text-red-300">Delete draft</button>}</div></details></div>
      </article>;
    })}</div>}
  </section>;
}
