// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/indie-game-profile/GameProfile.tsx": () => import("../components/mockups/indie-game-profile/GameProfile.tsx"),
  "./components/mockups/onboarding-games/Current.tsx": () => import("../components/mockups/onboarding-games/Current.tsx"),
  "./components/mockups/onboarding-games/Updated.tsx": () => import("../components/mockups/onboarding-games/Updated.tsx")
};
