// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/campaign-about/Current.tsx": () => import("../components/mockups/campaign-about/Current.tsx"),
  "./components/mockups/campaign-about/Revised.tsx": () => import("../components/mockups/campaign-about/Revised.tsx"),
  "./components/mockups/indie-game-profile/GameProfile.tsx": () => import("../components/mockups/indie-game-profile/GameProfile.tsx")
};
